CREATE TABLE IF NOT EXISTS SCHEMA_INDI_SOCIAIS.LOCAL (
    CHAVE_PAIS UUID DEFAULT uuid_generate_v1(),
    NOME_PAIS VARCHAR,
    SUB_REGIAO VARCHAR,
    CONTINENTE VARCHAR,

    CONSTRAINT  SCHEMA_INDI_LOCAL_PK PRIMARY KEY (CHAVE_PAIS)
);